env:
  es2021: true
  node: true
extends:
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ['./tsconfig.eslint.json']
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin-prettier'
rules: {}
